USE [master]
GO

/****** Object:  Database [Telekom_Neva_svyaz]    Script Date: 07.05.2022 17:51:29 ******/
CREATE DATABASE [Telekom_Neva_svyaz]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Telekom_Neva_svyaz', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Telekom_Neva_svyaz.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Telekom_Neva_svyaz_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Telekom_Neva_svyaz_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Telekom_Neva_svyaz].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET ARITHABORT OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET  MULTI_USER 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Telekom_Neva_svyaz] SET  READ_WRITE 
GO

