//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelekomNevaSvyaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Обрудование
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Обрудование()
        {
            this.История_изменений = new HashSet<История_изменений>();
            this.Порт_оборудования = new HashSet<Порт_оборудования>();
            this.Телефон = new HashSet<Телефон>();
        }
    
        public int ID_оборудование { get; set; }
        public int ID_тип_оборудования { get; set; }
        public string Наименование { get; set; }
        public int Серийный_норме { get; set; }
        public int MAC_адресс { get; set; }
        public string IP_адресс { get; set; }
        public System.DateTime Дата_уставноки { get; set; }
        public System.DateTime Дата_установки { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<История_изменений> История_изменений { get; set; }
        public virtual Тип_оборудования Тип_оборудования { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Порт_оборудования> Порт_оборудования { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Телефон> Телефон { get; set; }
    }
}
