//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelekomNevaSvyaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Порт_оборудования
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Порт_оборудования()
        {
            this.Использование_портов = new HashSet<Использование_портов>();
        }
    
        public int ID_порта { get; set; }
        public int ID_тип_порта { get; set; }
        public string IP_адресс { get; set; }
        public int ID_оборудования { get; set; }
        public int ID_количество_портов { get; set; }
        public string Статус_порта { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Использование_портов> Использование_портов { get; set; }
        public virtual Количество_портов Количество_портов { get; set; }
        public virtual Обрудование Обрудование { get; set; }
        public virtual Тип_порта Тип_порта { get; set; }
    }
}
