//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelekomNevaSvyaz
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Telekom_Neva_svyazEntities : DbContext
    {
        private static Telekom_Neva_svyazEntities entities;
        public Telekom_Neva_svyazEntities()
            : base("name=Telekom_Neva_svyazEntities")
        {
        }

        public static Telekom_Neva_svyazEntities GetContext()
        {
            if (entities == null)
                entities = new Telekom_Neva_svyazEntities();
            return entities;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Абонент> Абонент { get; set; }
        public virtual DbSet<Использование_портов> Использование_портов { get; set; }
        public virtual DbSet<История_изменений> История_изменений { get; set; }
        public virtual DbSet<Количество_портов> Количество_портов { get; set; }
        public virtual DbSet<Место_установки> Место_установки { get; set; }
        public virtual DbSet<Обрудование> Обрудование { get; set; }
        public virtual DbSet<Порт_оборудования> Порт_оборудования { get; set; }
        public virtual DbSet<Телефон> Телефон { get; set; }
        public virtual DbSet<Тип_оборудования> Тип_оборудования { get; set; }
        public virtual DbSet<Тип_порта> Тип_порта { get; set; }
    }
}
